# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20160512_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
