# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_registro_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='image',
            new_name='picture',
        ),
    ]
