# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_auto_20160514_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
