# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_auto_20160514_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='picture',
            field=models.ImageField(upload_to=b''),
        ),
    ]
